<% 
	objTextFile.WriteLine indent2 & "<additionalMetadata>"  'optional
    objTextFile.WriteLine indent3 & "<metadata>" 
    objTextFile.WriteLine indent4 & "<unitList>" 
    objTextFile.WriteLine indent5 & "<unit abbreviation=""mg/l"" id=""milligramsPerLiter"" multiplerToSI="".001""" 
    objTextFile.WriteLine indent5 & "name=""MilligramsPerLiter"" parentSI=""grams per cubic centimeter"" unitType=""massDensity"">" 
    objTextFile.WriteLine indent6 & "<description>per meter, describes optical properties</description>" 
    objTextFile.WriteLine indent5 & "</unit>" 
    objTextFile.WriteLine indent5 & "<unit abbreviation=""ug/l"" id=""microgramsPerLiter"" multiplerToSI="".0001""" 
    objTextFile.WriteLine indent5 & "name=""MilligramsPerLiter"" parentSI=""grams per cubic centimeter"" unitType=""massDensity"">" 
    objTextFile.WriteLine indent6 & "<description>per meter, describes optical properties</description>" 
    objTextFile.WriteLine indent5 & "</unit>" 
    objTextFile.WriteLine indent5 & "<unit abbreviation=""ft"" id=""foot"" multiplerToSI=""2.54""" 
    objTextFile.WriteLine indent5 & "name=""ft"" parentSI=""meter"" unitType=""length"">" 
    objTextFile.WriteLine indent6 & "<description>how long is something, describes physical properties</description>" 
    objTextFile.WriteLine indent5 & "</unit>" 
    objTextFile.WriteLine indent5 & "<unit abbreviation=""mph"" id=""milesperhour"" multiplerToSI="".44704""" 
    objTextFile.WriteLine indent5 & "name=""milesperhour"" parentSI=""meterspersecond"" unitType=""speed"">" 
    objTextFile.WriteLine indent6 & "<description>how fast is something going, describes physical properties</description>" 
    objTextFile.WriteLine indent5 & "</unit>" 
    objTextFile.WriteLine indent5 & "<unit abbreviation=""gC/m2/hr"" id=""gramsCarbonPerSquareMeterPerHour"" multiplerToSI="".00000001""" 
    objTextFile.WriteLine indent5 & "name=""CO2 Flux"" parentSI=""kilogramPerMeterQuaredPerHour"" unitType=""arealMassDensityRate"">" 
    objTextFile.WriteLine indent6 & "<description>Mass of a substance passing through a defined plane per unit of time.</description>" 
    objTextFile.WriteLine indent5 & "</unit>" 
    objTextFile.WriteLine indent5 & "<unit abbreviation=""ng N/cm2/hr"" id=""nanogramsNitrogenPerSquarecentimeterPerHour"" multiplerToSI="".00000001""" 
    objTextFile.WriteLine indent5 & "name=""Nitrous Oxide Flux"" parentSI=""kilogramPerMeterSuaredPerHour"" unitType=""arealMassDensityRate"">" 
    objTextFile.WriteLine indent6 & "<description>Mass of a substance passing through a defined plane per unit of time.</description>" 
    objTextFile.WriteLine indent5 & "</unit>" 
    objTextFile.WriteLine indent5 & "<unit abbreviation=""mgCH4/m2/day"" id=""milligramsMethanePerSquareMeterPerDay"" multiplerToSI="".00000004166""" 
    objTextFile.WriteLine indent5 & "name=""Methane Flux"" parentSI=""kilogramPerMeterQuaredPerHour"" unitType=""arealMassDensityRate"">" 
    objTextFile.WriteLine indent6 & "<description>Mass of a substance passing through a defined plane per unit of time.</description>" 
    objTextFile.WriteLine indent5 & "</unit>" 
    objTextFile.WriteLine indent5 & "<unit abbreviation=""ugCH4/hr"" id=""milligramsMethanePerHour"" multiplerToSI=""1""" 
    objTextFile.WriteLine indent5 & "name=""Denitrification enzyme activity"" parentSI=""microgramsperhour"" unitType=""arealMassDensityRate"">" 
    objTextFile.WriteLine indent6 & "<description>Mass of a substance per unit of time.</description>" 
    objTextFile.WriteLine indent5 & "</unit>" 
    objTextFile.WriteLine indent5 & "<unit abbreviation=""mgN/kg"" id=""milligramsNitrogenPerKilogram"" multiplerToSI=""1""" 
    objTextFile.WriteLine indent5 & "name=""KCL Extractable Nitrate"" parentSI=""milligramsperday"" unitType=""arealMassDensityRate"">" 
    objTextFile.WriteLine indent6 & "<description>Mass of a substance per mass of another</description>" 
    objTextFile.WriteLine indent5 & "</unit>" 
    objTextFile.WriteLine indent5 & "<unit abbreviation=""mgN/kg"" id=""milligramsAmmoniumPerKilogram"" multiplerToSI=""1""" 
    objTextFile.WriteLine indent5 & "name=""KCL Extractable Ammonium"" parentSI=""milligramsperday"" unitType=""arealMassDensityRate"">" 
    objTextFile.WriteLine indent6 & "<description>Mass of a substance per mass of another</description>" 
    objTextFile.WriteLine indent5 & "</unit>" 
    objTextFile.WriteLine indent5 & "<unit abbreviation=""mgN/kg"" id=""milligramsInorganicPerKilogram"" multiplerToSI=""1""" 
    objTextFile.WriteLine indent5 & "name=""KCL Extractable Inorganic Nitrogen"" parentSI=""milligramsperday"" unitType=""arealMassDensityRate"">" 
    objTextFile.WriteLine indent6 & "<description>Mass of a substance per mass of another</description>" 
    objTextFile.WriteLine indent5 & "</unit>" 
    objTextFile.WriteLine indent5 & "<unit abbreviation=""mgN/kg"" id=""MilligramsMicrobialNitrogenPerKilogram"" multiplerToSI=""1""" 
    objTextFile.WriteLine indent5 & "name=""Microbial Respiration"" parentSI=""milligramsperkilogram"" unitType=""arealMassDensityRate"">" 
    objTextFile.WriteLine indent6 & "<description>Mass of a substance per mass of another</description>" 
    objTextFile.WriteLine indent5 & "</unit>" 
    objTextFile.WriteLine indent5 & "<unit abbreviation=""mgN/kg/d"" id=""MilligramsMineralizedNitrogenPerKilogramPerDay"" multiplerToSI=""1""" 
    objTextFile.WriteLine indent5 & "name=""Potential net nitrogen mineralization (mgN/kg/d)"" parentSI=""milligramsperkilogramperday"" unitType=""arealMassDensityRate"">" 
    objTextFile.WriteLine indent6 & "<description>Concentration of a substance per day</description>" 
    objTextFile.WriteLine indent5 & "</unit>" 
    objTextFile.WriteLine indent5 & "<unit abbreviation=""gSoil/g"" id=""GramsSoilPerGram"" multiplerToSI=""1""" 
    objTextFile.WriteLine indent5 & "name=""Soil Organic Matter"" parentSI=""grampergram"" unitType=""arealMassDensityRate"">" 
    objTextFile.WriteLine indent6 & "<description>Concentration of a substance</description>" 
    objTextFile.WriteLine indent5 & "</unit>" 
    objTextFile.WriteLine indent5 & "<unit abbreviation=""gMoisture/g"" id=""GramsMoisturePerGram"" multiplerToSI=""1""" 
    objTextFile.WriteLine indent5 & "name=""Moisture Content"" parentSI=""grampergram"" unitType=""arealMassDensityRate"">" 
    objTextFile.WriteLine indent6 & "<description>Concentration of a substance</description>" 
    objTextFile.WriteLine indent5 & "</unit>" 
    objTextFile.WriteLine indent5 & "<unit abbreviation=""mgC/kg"" id=""MilligramsCarbonPerKilogram"" multiplerToSI=""1""" 
    objTextFile.WriteLine indent5 & "name=""Microbial Biomass of Carbon"" parentSI=""grampergram"" unitType=""arealMassDensityRate"">" 
    objTextFile.WriteLine indent6 & "<description>Concentration of a substance</description>" 
    objTextFile.WriteLine indent5 & "</unit>" 
    objTextFile.WriteLine indent5 & "<unit abbreviation=""mgN/kg"" id=""GramsMicrobialBiomassPerGram"" multiplerToSI=""1""" 
    objTextFile.WriteLine indent5 & "name=""Microbial Biomass of Nitrogen"" parentSI=""grampergram"" unitType=""arealMassDensityRate"">" 
    objTextFile.WriteLine indent6 & "<description>Concentration of a substance</description>" 
    objTextFile.WriteLine indent5 & "</unit>" 
    objTextFile.WriteLine indent5 & "<unit abbreviation=""gRoot/g"" id=""GramsRootPerGram"" multiplerToSI=""1""" 
    objTextFile.WriteLine indent5 & "name=""Root Biomass"" parentSI=""grampergram"" unitType=""arealMassDensityRate"">" 
    objTextFile.WriteLine indent6 & "<description>Concentration of a substance</description>" 
    objTextFile.WriteLine indent5 & "</unit>" 
    objTextFile.WriteLine indent5 & "<unit abbreviation=""ngN/g/hr"" id=""NanogramsNPerGramPerHour"" multiplerToSI="".000000001""" 
    objTextFile.WriteLine indent5 & "name=""Denitrification enzyme activity"" parentSI=""grampergramperhour"" unitType=""arealMassDensityRate"">" 
    objTextFile.WriteLine indent6 & "<description>Concentration of a substance</description>" 
    objTextFile.WriteLine indent5 & "</unit>" 
    objTextFile.WriteLine indent5 & "<unit abbreviation=""mgN/kg/day"" id=""MilligramsNitrogenPerKilogramPerDay"" multiplerToSI=""1""" 
    objTextFile.WriteLine indent5 & "name=""Microbial respiration"" parentSI=""milligramperkilogramperday"" unitType=""arealMassDensityRate"">" 
    objTextFile.WriteLine indent6 & "<description>Concentration of a substance</description>" 
    objTextFile.WriteLine indent5 & "</unit>" 
    objTextFile.WriteLine indent5 & "<unit abbreviation=""mgN/kg/day"" id=""MilligramsNitrogenPerKilogram"" multiplerToSI=""1""" 
    objTextFile.WriteLine indent5 & "name=""KCL Extractable Nitrate"" parentSI=""milligramperkilogram"" unitType=""arealMassDensityRate"">" 
    objTextFile.WriteLine indent6 & "<description>Concentration of a substance</description>" 
    objTextFile.WriteLine indent5 & "</unit>" 
    objTextFile.WriteLine indent4 & "</unitList>" 
    objTextFile.WriteLine indent3 & "</metadata>" 
    objTextFile.WriteLine indent2 & "</additionalMetadata>" 



%>



